# Generated by Django 4.1.7 on 2023-03-09 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedSurveyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('STARTED', 'Started')], default='STARTED', max_length=255, verbose_name='Survey status')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.TextField(verbose_name='Quest')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Survey name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Question description')),
                ('award', models.FloatField(default=0.0, verbose_name='Question award')),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.answermodel')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.questionmodel')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.completedsurveymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.surveymodel'),
        ),
        migrations.AddField(
            model_name='completedsurveymodel',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.surveymodel'),
        ),
        migrations.AddField(
            model_name='completedsurveymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.questionmodel'),
        ),
    ]
