# Generated by Django 4.1.7 on 2023-03-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractusermodel',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='abstractusermodel',
            name='border_color',
            field=models.CharField(
                default='#FFFFFF', max_length=255, verbose_name='Border color'),
        ),
        migrations.AddField(
            model_name='abstractusermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                         related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='abstractusermodel',
            name='is_superuser',
            field=models.BooleanField(
                default=False, verbose_name='Superuser status'),
        ),
        migrations.AddField(
            model_name='abstractusermodel',
            name='profile_background',
            field=models.CharField(
                default='#FFFFFF', max_length=255, verbose_name='Background profile'),
        ),
        migrations.AddField(
            model_name='abstractusermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set',
                                         related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
